- name: "organization.permission.organization: Grant permissions to team: [ {{ ansible_tower_config_organization_permission.team }} ]"
  when: "ansible_tower_config_organization_permission.state|default('present') == 'present'"
  command: |
    tower-cli role grant \
    --team "{{ ansible_tower_config_organization_permission.team }}" \
    --type "{{ ansible_tower_config_organization_permission.role }}" \
    --organization "{{ ansible_tower_config_organization_permission.organization }}"
  register: tower_cli_role_grant_organization
  changed_when: (tower_cli_role_grant_organization.stdout|from_json).changed|bool

- name: "organization.permission.organization: Revoke permissions from team: [ {{ ansible_tower_config_organization_permission.team }} ]"
  when: "ansible_tower_config_organization_permission.state|default('present') == 'absent'"
  command: |
    tower-cli role revoke \
    --team "{{ ansible_tower_config_organization_permission.team }}" \
    --type "{{ ansible_tower_config_organization_permission.role }}" \
    --organization "{{ ansible_tower_config_organization_permission.organization }}"
  register: tower_cli_role_revoke_organization
  changed_when: (tower_cli_role_revoke_organization.stdout|from_json).changed|bool
