- name: "organization.permission.target_team: Grant permissions to team: [ {{ ansible_tower_config_organization_permission.team }} ]"
  when: "ansible_tower_config_organization_permission.state|default('present') == 'present'"
  command: |
    tower-cli role grant \
    --team "{{ ansible_tower_config_organization_permission.team }}" \
    --type "{{ ansible_tower_config_organization_permission.role }}" \
    --target-team "{{ ansible_tower_config_organization_permission.target_team }}"
  register: tower_cli_role_grant_target_team
  changed_when: (tower_cli_role_grant_target_team.stdout|from_json).changed|bool

- name: "organization.permission.target_team: Revoke permissions from team: [ {{ ansible_tower_config_organization_permission.team }} ]"
  when: "ansible_tower_config_organization_permission.state|default('present') == 'absent'"
  command: |
    tower-cli role revoke \
    --team "{{ ansible_tower_config_organization_permission.team }}" \
    --type "{{ ansible_tower_config_organization_permission.role }}" \
    --target-team "{{ ansible_tower_config_organization_permission.target_team }}"
  register: tower_cli_role_revoke_target_team
  changed_when: (tower_cli_role_revoke_target_team.stdout|from_json).changed|bool
