- name: "Configure Variables"
  import_tasks: "config/variables.yml"

- name: "Configure License"
  import_tasks: "config/license.yml"
  when: ansible_tower_config.license is mapping

- name: "Configure Organization"
  import_tasks: "config/organization.yml"
  when: ansible_tower_config.organization is mapping
