- name: "config.setting-cli.license: MODIFY LICENSE"
  shell: tower-cli setting modify LICENSE {{ ansible_tower_config.setting.license | from_yaml | to_json | quote  }}
  register: tower_cli_setting_modify_license
