- name: "organization.inventory: Ensure state of inventory: [ {{ ansible_tower_config_organization_inventory.name }} ]"
  tower_inventory:
    name: "{{ ansible_tower_config_organization_inventory.name }}"
    organization:  "{{ ansible_tower_config_organization.name }}"
    description: "{{ ansible_tower_config_organization_inventory.description | default(omit) }}"
    state: "{{ ansible_tower_config_organization_inventory.state | default(omit) }}"

#- name: "organizations.inventory: Process [ sources ]"
#  when: ansible_tower_config_organization_inventory.sources is sequence
#  include_tasks: "inventory/source.yml"
#  loop: "{{ ansible_tower_config_organization_inventory.sources }}"
#  loop_control:
#      loop_var: ansible_tower_config_organization_inventory_source
#      label: "{{ ansible_tower_config_organization_inventory_source.name }}"

## Functionality not available in the module today
- name: "organizations.inventory: Process [ sources ] with tower-cli"
  when: ansible_tower_config_organization_inventory.sources is sequence
  include_tasks: "inventory/source-cli.yml"
  loop: "{{ ansible_tower_config_organization_inventory.sources }}"
  loop_control:
      loop_var: ansible_tower_config_organization_inventory_source
      label: "{{ ansible_tower_config_organization_inventory_source.name }}"
