- name: "config.organization.permission-cli: Ensure permissions for role [ {{ tower_config_organization_permission.role }} ]"
  command: "{{ lookup('template', 'permission-cli.j2') }}"
  register: tower_cli_permission
