---
- name: "config.organization.permission-cli: [ {{ tower_config_organization_permission.role }} ]"
  command: "{{ lookup('template', 'permission-cli.j2') }}"
  register: tower_cli_permission
  when: tower_config_organization_permission.role is defined
