- name: "config.organization.permission: Ensure permissions for role [ {{ tower_config_organization_permission.role }} ]"
  tower_role:
    role: "{{ tower_config_organization_permission.role }}"
    team: "{{ tower_config_organization_permission.team | default(omit) }}"
    user: "{{ tower_config_organization_permission.user | default(omit) }}"
    credential: "{{ tower_config_organization_permission.credential | default(omit) }}"
    inventory: "{{ tower_config_organization_permission.inventory | default(omit) }}"
    job_template: "{{ tower_config_organization_permission.job_template | default(omit) }}"
    organization: "{{ tower_config_organization_permission.organization | default(omit) }}"
    project: "{{ tower_config_organization_permission.project | default(omit) }}"
    target_team: "{{ tower_config_organization_permission.target_team | default(omit) }}"
    state: "{{ tower_config_organization_permission.state | default(omit) }}"
