---
- name: "config.organization.project: Ensure state of project: [ {{ ansible_tower_config_organization_project }} ]"
  tower_project:
    tower_config_file: "~/.tower_cli.cfg"
    organization: "{{ ansible_tower_config_organization.name }}"
    name: "{{ ansible_tower_config_organization_project.name }}"
    description: "{{ ansible_tower_config_organization_project.description | default(omit) }}"
    scm_credential: "{{ ansible_tower_config_organization_project.scm_credential | default(omit) }}"
    scm_type: "{{ ansible_tower_config_organization_project.scm_type | default(omit) }}"
    scm_branch: "{{ ansible_tower_config_organization_project.scm_branch | default(omit) }}"
    scm_update_on_launch: "{{ ansible_tower_config_organization_project.scm_update_on_launch | default(omit) }}"
    scm_url: "{{ ansible_tower_config_organization_project.scm_url | default(omit) }}"
    state: "{{ ansible_tower_config_organization_project.state | default(omit) }}"
