---
- name: "config.organization.team: Ensure state of team: [ {{ ansible_tower_config_organization_team.name }} ]"
  tower_team:
    name: "{{ ansible_tower_config_organization_team.name }}"
    organization: "{{ ansible_tower_config_organization.name }}"
    description: "{{ ansible_tower_config_organization_team.description | default(omit) }}"
    state: "{{ ansible_tower_config_organization_team.state | default(omit) }}"

## Functionality not available in the module today
- name: "config.organization.team: Ensure membership of team: [ {{ ansible_tower_config_organization_team.name }} ] with tower-cli"
  when: ansible_tower_config_organization_team.members is sequence
  include_tasks: "team/member-cli.yml"
  loop: "{{ ansible_tower_config_organization_team.members }}"
  loop_control:
    loop_var: ansible_tower_config_organization_team_member
    label: "{{ ansible_tower_config_organization_team_member.name }}"
