---
- name: "config.organization.user: Ensure state of user: [ {{ tower_config_organization_user.name }} ]"
  tower_user:
    username:   "{{ tower_config_organization_user.name       }}"
    password:   "{{ tower_config_organization_user.password   }}"
    email:      "{{ tower_config_organization_user.email      }}"
    first_name: "{{ tower_config_organization_user.first_name }}"
    last_name:  "{{ tower_config_organization_user.last_name  }}"
    superuser:  "{{ tower_config_organization_user.superuser|bool | default(omit) }}"
    auditor:    "{{ tower_config_organization_user.auditor|bool   | default(omit) }}"
    state:      "{{ tower_config_organization_user.state          | default(omit) }}"

- name: "config.organization.permission: Ensure membership in Organization for user: [ {{ tower_config_organization_user.name }} ]"
  tower_role:
    user:         "{{ tower_config_organization_user.name }}"
    organization: "{{ tower_config_organization.name }}"
    role:         "member"
    state:        "present"
