---
- name: "config.organization.user: Ensure state of user: [ {{ ansible_tower_config_organization_user.name }} ]"
  tower_user:
    username: "{{ ansible_tower_config_organization_user.name }}"
    password: "{{ ansible_tower_config_organization_user.password }}"
    email: "{{ ansible_tower_config_organization_user.email }}"
    first_name: "{{ ansible_tower_config_organization_user.first_name }}"
    last_name: "{{ ansible_tower_config_organization_user.last_name }}"
    superuser: "{{ ansible_tower_config_organization_user.superuser | default(omit) }}"
    auditor: "{{ ansible_tower_config_organization_user.auditor | default(omit) }}"
    state: "{{ ansible_tower_config_organization_user.state | default(omit) }}"
