---
- name: "config.organization: Process [ organization ]"
  when: tower_config_organization is defined
  include_tasks: "organization/main.yml"
  vars:
    tower_config_organization: "{{ tower_config_organization_dict.value | default({}) }}"
  with_dict: "{{ tower_config.organization | default({}) }}"
  loop_control:
    loop_var: tower_config_organization_dict
    label: "{{ tower_config_organization_dict.key }}"
