---
- name: "config.organization.team.member-cli: [ {{ tower_config_organization_team.name }} ]"
  command: "{{ lookup('template', 'member-cli.j2') }}"
  register: tower_cli_team
  when: tower_config_organization_team.name is defined
